### ISSUE TITLE
about training code

### ISSUE THREAD

**Issue by Vebrun** [krishnaone/Speech-Emotion-Recognition-using-MFCCs#1]
Hello, your project is really great, but there is no training code to train different model, can you share your training code, thank you!

**Comment by Towardscybersec** [comment]
> Hello, your project is really great, but there is no training code to train different model, can you share your training code, thank you!

Hey, All the Exploratory Data Analysis and model code will be released after publishing the project's Research Paper.
Thank you so much for your response.

**Comment by Vebrun** [comment]
ok .  I see. Thank you!
